
# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: develop
        
    - name: Execute tests 
      run: |
        docker run \
        -e SONAR_HOST_URL=${{ secrets.SONARQUBE_HOST }} \
        -e SONAR_LOGIN=${{ secrets.SONARQUBE_TOKEN }} \
        -e SONAR_PROJECT_BASE_DIR=./sonarqube-scanner \
        -Dsonar.projectName=pj2_develop \
        -Dsonar.projectKey=pj2_develop \
        -Dsonar..sourceEncoding=UTF-8 \
        -Dsonar.projectVersion=${{ github.run_id }} \
        -DSRC_PATH=./ \
        sonarsource/sonar-scanner-cli
